window.runSelfTest = () => {
  const results = [];
  const assert = (name, cond) => results.push({ name, pass: !!cond });
  const snap = Store.snapshot();
  const undoSnap = Store.undoStack;
  const prefsSnap = { ...Store.state.prefs };
  const recentSnap = Store.state.recent.slice();
  const lsKeys = Object.values(KEYS).concat(['lx_current_order']);
  const lsSnap = lsKeys.map(k => [k, localStorage.getItem(k)]);
  const reset = () => { Store.restore({ lines: new Map(), orders: [], current: -1, draftName: '' }); Store.undoStack = []; };
  const concor = App.db.find(d => d.n === 'Concor 5');
  const dyn = App.db.find(d => d.isDynamic);
  const toujeo = App.db.find(d => d.n === 'Toujeo' && d.tierId === 'workforce');
  const press = (target, key, o = {}) => { if (target === els.in) els.in.focus(); const ev = new KeyboardEvent('keydown', { key, bubbles: true, cancelable: true, shiftKey: !!o.shift, ctrlKey: !!o.ctrl }); target.dispatchEvent(ev); return ev; };

  document.documentElement.classList.remove('booting');
  void document.body.offsetHeight;
  try {
    assert('data: catalog loaded from drugs.json', App.db.length === App.data.items.length && App.db.length > 100);
    assert('data: every item resolves to a known engine', App.db.every(i => App.data.engines[i.engineId]));
    assert('ids: unique across catalog', new Set(App.db.map(d => d.id)).size === App.db.length);
    assert('ids: stable v4.5-compatible id for tiered item', toujeo.id === makeStableId('Toujeo قوي عاملة', 'Pen', 'شراء موحد'));
    assert('engine: insulin gets IU base units', toujeo.bType === 'IU' && toujeo.bQty === 450);
    assert('engine: standard insulin pen is 300 IU', App.db.find(d => d.n === 'Novorapid').bQty === 300);
    assert('engine: pack item parses base count', concor.bQty === 30 && concor.bType === 'Tab');

    const p1 = packInfo(310, 300);
    assert('pack math: 310/300 → 2 packs, 290 spare', p1.packs === 2 && p1.spare === 290);
    assert('pack math: exact multiple has no spare', packInfo(300, 300).spare === 0);
    assert('pack math: missing bQty falls back to 1', packInfo(5).packs === 5);
    assert('money: 11.5 → 1150 piastres', toPiastres(11.5) === 1150 && money(1150) === '11.50');
    assert('cost: supply share is 50% × packs', costOf(dyn, 2, 100) === 10000);
    assert('cost: fixed is packs × pack price', costOf(concor, 3) === 3 * concor.pP);

    [['concor 5', 'concor 5', null, null, null], ['concor 5 x30', 'concor 5', 30, 'default', null], ['concor 5x30', 'concor 5', 30, 'default', null], ['amaryl * 2', 'amaryl', 2, 'default', null], ['concor 5 x2p', 'concor 5', 2, 'pack', null], ['concor 5 x30u', 'concor 5', 30, 'unit', null], ['atozet 10 / 20 x3', 'atozet 10/20', 3, 'default', null], ['anoro @450 x2', 'anoro', 2, 'default', 450], ['anoro x2 @450', 'anoro', 2, 'default', 450], ['novomix 30', 'novomix 30', null, null, null], ['concor ٥ x٣٠', 'concor 5', 30, 'default', null], ['concor 5 x', 'concor 5 x', null, null, null], ['x30', 'x30', null, null, null], ['concor 5 x1000000', 'concor 5', 999999, 'default', null]].forEach(([i, q, n, u, p]) => {
      const r = parseCommand(i);
      assert(`parse: ${JSON.stringify(i)}`, r.query === q && r.qty === n && r.unit === u && r.price === p);
    });
    assert('parse: x0 is rejected', parseCommand('concor 5 x0').qtyInvalid === true);

    const s1 = searchCatalog(App.db, 'concor 5');
    assert('search: exact name ranks first', s1[0].n === 'Concor 5');
    assert('search: generic alias finds brand', searchCatalog(App.db, 'glimepiride')[0].n.startsWith('Amaryl'));
    assert('search: typo tolerance (lipitr → Lipitor)', searchCatalog(App.db, 'lipitr').some(i => i.n.startsWith('Lipitor')));
    assert('search: arabic tier text matches', searchCatalog(App.db, 'طلاب').length > 0 && searchCatalog(App.db, 'طلاب').every(i => i.tierId === 'students'));
    assert('search: english tier alias matches', searchCatalog(App.db, 'toujeo students').length === 1);
    assert('search: tight slash equals spaced slash', searchCatalog(App.db, 'atozet 10/20')[0].n === 'Atozet 10 / 20');
    assert('search: type facet restricts results', searchCatalog(App.db, '', { type: 'insulin' }).every(i => i.engineId === 'insulin'));
    assert('search: no match returns empty', searchCatalog(App.db, 'zzznonexistentxyz').length === 0);
    assert('suggest: close typo of generic suggests brand', suggestFor(App.db, 'bisoprolo') === 'Concor');
    assert('suggest: short query yields nothing', suggestFor(App.db, 'xyz') === null);

    reset();
    const bad = Store.add(concor.id, 0);
    assert('store: rejects zero quantity', !bad.ok && bad.reason === 'invalid-qty' && Store.state.lines.size === 0);
    const np = Store.add(dyn.id, 2, NaN);
    assert('store: share item needs price', !np.ok && np.reason === 'needs-price');
    const a1 = Store.add(concor.id, 45);
    assert('store: add computes packs & spare', a1.ok && a1.packs === 2 && a1.spare === 15);
    Store.add(concor.id, 5);
    assert('store: additive add sums requests', Store.state.lines.get(concor.id).req === 50);
    const e1 = Store.edit(concor.id, 'req', 61);
    assert('store: edit req recomputes packs', e1.packs === 3);
    const e2 = Store.edit(concor.id, 'pack', 5);
    assert('store: edit pack recomputes cost', e2.costP === 5 * concor.pP);
    const e3 = Store.edit(concor.id, 'req', 5000000);
    assert('store: edit clamps to max', e3.clamped && e3.req === MAX_QTY);

    reset();
    App.db.filter(d => !d.isDynamic).slice(0, 5).forEach(d => Store.add(d.id, 10));
    assert('undo: 5 adds → 5 lines', Store.state.lines.size === 5 && Store.undoStack.length === 5);
    for (let i = 0; i < 5; i++) Store.undo();
    assert('undo: 5 undos → empty, 0.00 total', Store.state.lines.size === 0 && money(Store.totalP()) === '0.00');
    Store.add(concor.id, 30); Store.remove(concor.id); Store.undo();
    assert('undo: removal restores the line', Store.state.lines.get(concor.id).req === 30);
    Store.clear(); Store.undo();
    assert('undo: clear is reversible', Store.state.lines.has(concor.id));

    reset();
    Store.add(concor.id, 30);
    Store.saveOrder();
    assert('orders: save creates active order', Store.state.orders.length === 1 && Store.state.current === 0);
    Store.add(concor.id, 30);
    assert('orders: active order syncs edits', Store.state.orders[0].lines.get(concor.id).req === 60);
    Store.newOrder();
    Store.add(dyn.id, 1, 200);
    const lo = Store.loadOrder(0);
    assert('orders: switching keeps unsaved work as order', lo.ok && lo.autosaved && Store.state.orders.length === 2);
    const dn = Store.deleteOrder(1);
    Store.undo();
    assert('orders: delete is undoable', dn && Store.state.orders.length === 2);
    assert('orders: duplicate works', Store.duplicateOrder(0).ok && Store.state.orders.length === 3);

    reset();
    const legacy = [['old-random-id', { req: 5, packs: 1, cost: 10, supplyPrice: 0, item: { n: 'Toujeo', t: 'قوي عاملة', u: 'Pen', s: 'Unified Purchase' } }], ['x', { item: { n: 'nope' } }], ['bad']];
    const hyd = Store.hydrateEntries(legacy);
    assert('migration: v4.5 entry remaps to current id', hyd.length === 1 && hyd[0][0] === toujeo.id);
    const imp = Store.importEntries({ title: 'Legacy', items: legacy });
    assert('import: drops unknown, keeps valid', imp.ok && imp.count === 1 && imp.dropped === 2);

    reset();
    Store.state.prefs.addMode = 'unit';
    els.in.value = ''; App.armed = false; search();
    assert('omni: empty is IDLE', App.omniState === 'IDLE');
    els.in.value = 'concor'; App.armed = false; search();
    assert('omni: text is SEARCHING', App.omniState === 'SEARCHING');
    els.in.value = 'concor 5 x30'; App.armed = false; search();
    assert('omni: qty is ARMED_WITH_QTY', App.omniState === 'ARMED_WITH_QTY');
    els.in.value = `${dyn.n} x2`; App.armed = false; search();
    assert('omni: share item without price NEEDS_PRICE', App.omniState === 'ARMED_NEEDS_PRICE');
    els.in.value = `${dyn.n} @450 x2`; App.armed = false; search();
    assert('omni: @price skips NEEDS_PRICE', App.omniState === 'ARMED_WITH_QTY');
    els.in.value = 'concor'; App.armed = false; search();
    press(els.in, 'Tab');
    assert('omni: Tab completes & arms', App.armed && App.omniState === 'ARMED_PENDING_QTY');
    els.in.value = 'concor 5 x30'; App.armed = false; search();
    press(els.in, 'Escape');
    assert('omni: Esc strips qty', els.in.value === 'concor 5' && App.omniState === 'SEARCHING');
    press(els.in, 'Escape');
    assert('omni: Esc again clears', els.in.value === '' && App.omniState === 'IDLE');
    els.in.value = 'concor 5 x30'; App.armed = false; search();
    press(els.in, 'Enter');
    assert('loop: Enter commits and returns to IDLE', Store.state.lines.get(concor.id).req === 30 && App.omniState === 'IDLE' && document.activeElement === els.in);
    els.in.value = 'concor 5 x5'; App.armed = false; search();
    press(els.in, 'Enter', { shift: true });
    assert('loop: Shift+Enter keeps query', els.in.value === 'concor 5 x5' && Store.state.lines.get(concor.id).req === 35);
    press(els.in, 'Enter');
    assert('loop: repeat Enter adds again', Store.state.lines.get(concor.id).req === 40);
    els.in.value = 'toujeo x900u'; App.armed = false; search();
    press(els.in, 'Enter');
    const tj = Store.state.lines.get(searchCatalog(App.db, 'toujeo')[0].id);
    assert('loop: insulin IU → pens (900u → 2)', tj && tj.packs === 2);
    els.in.value = 'concor 5 x2p'; App.armed = false; search();
    press(els.in, 'Enter');
    assert('loop: x2p adds packs', Store.state.lines.get(concor.id).req === 100);
    els.in.value = `${dyn.n} x2`; App.armed = false; search();
    press(els.in, 'Enter');
    assert('price: Enter reveals price field', !els.priceWrap.hidden && document.activeElement === els.price);
    els.price.value = '450';
    press(els.price, 'Enter');
    assert('price: Enter in price commits', Store.state.lines.has(dyn.id) && App.omniState === 'IDLE');
    els.in.value = 'concor'; search();
    moveSel(1);
    assert('select: down selects first', App.sel === 0 && els.in.getAttribute('aria-activedescendant') === `row-${App.results[0].id}`);
    moveSel(-1);
    assert('select: up wraps to last', App.sel === App.results.length - 1);
    const firstNode = rowCache.get(App.results[0].id);
    els.in.value = 'concor '; search();
    assert('render: surviving row keeps DOM node', rowCache.get(App.results[0].id) === firstNode);
    assert('a11y: listbox/option/combobox', els.res.getAttribute('role') === 'listbox' && firstNode.getAttribute('role') === 'option' && els.in.getAttribute('role') === 'combobox');
    els.in.value = ''; search();
    assert('idle: empty query shows idle panel', !!els.res.querySelector('[data-idle]') && App.results.length === 0);
    els.in.value = 'zzznonexistentxyz'; search();
    assert('empty: no-match names query', els.res.textContent.includes('zzznonexistentxyz'));
  } finally {
    Store.restore(snap);
    Store.undoStack = undoSnap;
    Object.assign(Store.state.prefs, prefsSnap);
    Store.state.recent = recentSnap;
    lsSnap.forEach(([k, v]) => { if (v === null) localStorage.removeItem(k); else localStorage.setItem(k, v); });
    els.in.value = ''; App.armed = false; els.priceWrap.hidden = true;
    search(); renderTray(); renderModeSeg();
    $('toasts').innerHTML = '';
  }
  const pass = results.filter(r => r.pass).length;
  console.group(`%cLX self-test: ${pass}/${results.length} passed`, `color:${pass === results.length ? '#3ddc84' : '#ff5c5c'};font-weight:bold`);
  results.forEach(r => console[r.pass ? 'log' : 'error'](`${r.pass ? '✓' : '✗'} ${r.name}`));
  console.groupEnd();
  return results;
};
