window.runSelfTest = () => {
  const results = [];
  const assert = (name, cond) => results.push({ name, pass: !!cond });
  const snap = Store.snapshot();
  const undoSnap = Store.undoStack;
  const prefsSnap = JSON.parse(JSON.stringify(Store.state.prefs));
  const recentSnap = Store.state.recent.slice();
  const lsKeys = Object.values(KEYS);
  const lsSnap = lsKeys.map(k => [k, localStorage.getItem(k)]);
  const reset = () => { Store.restore({ calcs: [], active: null, seq: 0 }); Store.undoStack = []; Store.state.prefs.rounding = {}; Store.state.prefs.minOne = true; };
  const concor = App.db.find(d => d.n === 'Concor 5');
  const dyn = App.db.find(d => d.isDynamic);
  const toujeo = App.db.find(d => d.n === 'Toujeo' && d.tierId === 'workforce');
  const apidra = App.db.find(d => d.n === 'Apidra' && d.tierId === 'students');
  const press = (target, key, o = {}) => { if (target === els.in) els.in.focus(); const ev = new KeyboardEvent('keydown', { key, bubbles: true, cancelable: true, shiftKey: !!o.shift, ctrlKey: !!o.ctrl }); target.dispatchEvent(ev); return ev; };

  document.documentElement.classList.remove('booting');
  void document.body.offsetHeight;
  try {
    assert('data: catalog loaded from drugs.json', App.db.length === App.data.items.length && App.db.length > 100);
    assert('data: every item resolves to a known engine', App.db.every(i => App.data.engines[i.engineId]));
    assert('ids: unique across catalog', new Set(App.db.map(d => d.id)).size === App.db.length);
    assert('ids: stable v4.5-compatible id for tiered item', toujeo.id === makeStableId('Toujeo قوي عاملة', 'Pen', 'شراء موحد'));
    assert('engine: insulin gets IU base units', toujeo.bType === 'IU' && toujeo.bQty === 450);
    assert('engine: standard insulin pen is 300 IU', App.db.find(d => d.n === 'Novorapid').bQty === 300);
    assert('engine: pack item parses base count', concor.bQty === 30 && concor.bType === 'Tab');

    assert('round: 3.4 nearest → 3', packInfo(1020, 300, 'round').packs === 3);
    assert('round: 3.4 up → 4', packInfo(1020, 300, 'ceil').packs === 4);
    assert('round: 3.4 down → 3', packInfo(1020, 300, 'floor').packs === 3);
    assert('round: 3.6 nearest → 4', packInfo(1080, 300, 'round').packs === 4);
    assert('round: 3.5 nearest → 4', packInfo(105, 30, 'round').packs === 4);
    assert('round: short reported when rounding down', packInfo(1020, 300, 'floor').short === 120 && packInfo(1020, 300, 'floor').spare === 0);
    assert('round: spare reported when rounding up', packInfo(1020, 300, 'ceil').spare === 180);
    assert('round: exact multiple has no spare or short', packInfo(300, 300, 'ceil').spare === 0 && packInfo(300, 300).short === 0);
    assert('round: min-one lifts 0 → 1', packInfo(50, 300, 'round', true).packs === 1 && packInfo(50, 300, 'round', false).packs === 0);
    assert('round: float noise does not bump ceil', packInfo(0.3 * 30, 3, 'ceil').packs === 3);
    assert('round: default mode is nearest', DEFAULT_ROUND === 'round' && packInfo(1020, 300).packs === 3);
    assert('money: 11.5 → 1150 piastres', toPiastres(11.5) === 1150 && money(1150) === '11.50');
    assert('cost: supply share is 50% × packs', costOf(dyn, 2, 100) === 10000);
    assert('cost: fixed is packs × pack price', costOf(concor, 3) === 3 * concor.pP);

    [['concor 5', 'concor 5', null, null, null, null], ['concor 5 x30', 'concor 5', 30, 'default', null, null], ['concor 5x30', 'concor 5', 30, 'default', null, null], ['amaryl * 2', 'amaryl', 2, 'default', null, null], ['concor 5 x2p', 'concor 5', 2, 'pack', null, null], ['concor 5 x30u', 'concor 5', 30, 'unit', null, null], ['atozet 10 / 20 x3', 'atozet 10/20', 3, 'default', null, null], ['anoro @450 x2', 'anoro', 2, 'default', 450, null], ['anoro x2 @450', 'anoro', 2, 'default', 450, null], ['novomix 30', 'novomix 30', null, null, null, null], ['concor ٥ x٣٠', 'concor 5', 30, 'default', null, null], ['concor 5 x', 'concor 5 x', null, null, null, null], ['x30', 'x30', null, null, null, null], ['concor 5 x1000000', 'concor 5', 999999, 'default', null, null], ['concor 5 x30 #2', 'concor 5', 30, 'default', null, 2], ['#3 concor 5 x30', 'concor 5', 30, 'default', null, 3], ['anoro #2 @450 x2', 'anoro', 2, 'default', 450, 2], ['concor 5 # 4', 'concor 5', null, null, null, 4]].forEach(([i, q, n, u, p, c]) => {
      const r = parseCommand(i);
      assert(`parse: ${JSON.stringify(i)}`, r.query === q && r.qty === n && r.unit === u && r.price === p && r.calc === c);
    });
    assert('parse: x0 is rejected', parseCommand('concor 5 x0').qtyInvalid === true);

    const s1 = searchCatalog(App.db, 'concor 5');
    assert('search: exact name ranks first', s1[0].n === 'Concor 5');
    assert('search: generic alias finds brand', searchCatalog(App.db, 'glimepiride')[0].n.startsWith('Amaryl'));
    assert('search: typo tolerance (lipitr → Lipitor)', searchCatalog(App.db, 'lipitr').some(i => i.n.startsWith('Lipitor')));
    assert('search: arabic tier text matches', searchCatalog(App.db, 'طلاب').length > 0 && searchCatalog(App.db, 'طلاب').every(i => i.tierId === 'students'));
    assert('search: english tier alias matches', searchCatalog(App.db, 'toujeo students').length === 1);
    assert('search: tight slash equals spaced slash', searchCatalog(App.db, 'atozet 10/20')[0].n === 'Atozet 10 / 20');
    assert('search: type facet restricts results', searchCatalog(App.db, '', { type: 'insulin' }).every(i => i.engineId === 'insulin'));
    assert('search: no match returns empty', searchCatalog(App.db, 'zzznonexistentxyz').length === 0);
    assert('suggest: close typo of generic suggests brand', suggestFor(App.db, 'bisoprolo') === 'Concor');
    assert('suggest: short query yields nothing', suggestFor(App.db, 'xyz') === null);

    reset();
    assert('workspace: always at least one calculation', Store.state.calcs.length === 1 && Store.activeCalc());
    const bad = Store.add(concor.id, 0);
    assert('store: rejects zero quantity', !bad.ok && bad.reason === 'invalid-qty' && Store.state.lines.size === 0);
    const np = Store.add(dyn.id, 2, NaN);
    assert('store: share item needs price', !np.ok && np.reason === 'needs-price');
    const a1 = Store.add(concor.id, 45);
    assert('store: 45 tabs / 30 → nearest 2 packs, 15 spare', a1.ok && a1.packs === 2 && a1.spare === 15);
    Store.add(concor.id, 5);
    assert('store: additive add sums requests', Store.state.lines.get(concor.id).req === 50);
    const e1 = Store.edit(concor.id, 'req', 61);
    assert('store: edit req recomputes packs (2.03 → 2)', e1.packs === 2 && e1.short === 1);
    const e2 = Store.edit(concor.id, 'pack', 5);
    assert('store: edit pack recomputes cost & flags manual', e2.costP === 5 * concor.pP && Store.state.lines.get(concor.id).manual);
    assert('store: resetPacks returns to automatic', Store.resetPacks(concor.id) && Store.state.lines.get(concor.id).packs === 2 && !Store.state.lines.get(concor.id).manual);
    const e3 = Store.edit(concor.id, 'req', 5000000);
    assert('store: edit clamps to max', e3.clamped && e3.req === MAX_QTY);

    reset();
    Store.add(apidra.id, 1020);
    assert('rounding: insulin 3.4 pens → 3 by default', Store.state.lines.get(apidra.id).packs === 3);
    const changed = Store.setRounding('insulin', 'ceil');
    assert('rounding: switching to up reflows existing lines', changed === 1 && Store.state.lines.get(apidra.id).packs === 4);
    Store.add(concor.id, 31);
    assert('rounding: per-engine — pack items stay nearest', Store.state.lines.get(concor.id).packs === 1);
    Store.edit(apidra.id, 'pack', 9);
    Store.setRounding('insulin', 'floor');
    assert('rounding: manual packs survive a rule change', Store.state.lines.get(apidra.id).packs === 9);
    Store.resetPacks(apidra.id);
    assert('rounding: floor after reset → 3', Store.state.lines.get(apidra.id).packs === 3);
    Store.setMinOne(false);
    Store.edit(concor.id, 'req', 10);
    assert('rounding: min-one off allows 0 packs', Store.state.lines.get(concor.id).packs === 0);
    Store.setMinOne(true);
    assert('rounding: min-one on lifts back to 1', Store.state.lines.get(concor.id).packs === 1);
    Store.state.prefs.rounding = {}; Store.state.prefs.minOne = true;

    reset();
    App.db.filter(d => !d.isDynamic).slice(0, 5).forEach(d => Store.add(d.id, 10));
    assert('undo: 5 adds → 5 lines', Store.state.lines.size === 5 && Store.undoStack.length === 5);
    for (let i = 0; i < 5; i++) Store.undo();
    assert('undo: 5 undos → empty, 0.00 total', Store.state.lines.size === 0 && money(Store.totalP()) === '0.00');
    Store.add(concor.id, 30); Store.remove(concor.id); Store.undo();
    assert('undo: removal restores the line', Store.state.lines.get(concor.id).req === 30);
    Store.clear(); Store.undo();
    assert('undo: clear is reversible', Store.state.lines.has(concor.id));
    const before = Store.undoStack.length;
    Store.edit(concor.id, 'req', 31); Store.edit(concor.id, 'req', 32); Store.edit(concor.id, 'req', 33);
    assert('undo: rapid edits to one field coalesce', Store.undoStack.length === before + 1);

    reset();
    const c1 = Store.activeCalc();
    Store.add(concor.id, 30);
    const c2 = Store.newCalc('Patient B').calc;
    assert('calcs: new calculation becomes active', Store.state.active === c2.id && Store.state.calcs.length === 2);
    assert('calcs: new calc gets a distinct color', c1.hue !== c2.hue);
    Store.add(concor.id, 60);
    assert('calcs: lines are independent per calc', c1.lines.get(concor.id).req === 30 && c2.lines.get(concor.id).req === 60);
    Store.add(apidra.id, 300, 0, true, c1.id);
    assert('calcs: add can target a non-active calc', c1.lines.has(apidra.id) && !c2.lines.has(apidra.id) && Store.state.active === c2.id);
    const mem = Store.membership(concor.id);
    assert('calcs: membership lists every calc holding an item', mem.length === 2 && mem.find(m => m.active).calc === c2 && mem[0].pos === 1);
    Store.switchTo(c1.id);
    assert('calcs: switching keeps both calcs intact', Store.state.active === c1.id && Store.state.lines.size === 2 && c2.lines.size === 1);
    const t1 = Store.transferLine(apidra.id, c1.id, c2.id, 'move');
    assert('calcs: move transfers a line', t1.ok && !c1.lines.has(apidra.id) && c2.lines.get(apidra.id).req === 300);
    const t2 = Store.transferLine(concor.id, c1.id, c2.id, 'copy');
    assert('calcs: copy combines with existing line', t2.ok && t2.merged && c1.lines.has(concor.id) && c2.lines.get(concor.id).req === 90 && c2.lines.get(concor.id).packs === 3);
    Store.undo();
    assert('calcs: transfer is undoable', Store.calc(c2.id).lines.get(concor.id).req === 60 && Store.calc(c1.id).lines.has(concor.id));
    const t3 = Store.transferLine(concor.id, c1.id, '__new', 'copy');
    assert('calcs: transfer to a new calculation', t3.ok && Store.state.calcs.length === 3 && t3.to.lines.get(concor.id).req === 30);
    Store.undo();
    const d1 = Store.duplicateCalc(Store.state.calcs[1].id);
    assert('calcs: duplicate inserts after source', d1.ok && Store.state.calcs[2].id === d1.calc.id && d1.calc.lines.size === Store.state.calcs[1].lines.size);
    Store.moveCalc(d1.calc.id, 0);
    assert('calcs: reorder moves a calc', Store.state.calcs[0].id === d1.calc.id && Store.byPosition(1).id === d1.calc.id);
    Store.undo();
    const m1 = Store.mergeCalc(d1.calc.id, Store.state.calcs[1].id);
    const tgt = Store.state.calcs[1];
    assert('calcs: merge folds lines & removes source', m1.ok && Store.state.calcs.length === 2 && tgt.lines.get(concor.id).req === 120 && !Store.calc(d1.calc.id));
    Store.undo();
    assert('calcs: merge is undoable', Store.state.calcs.length === 3);
    const grand = Store.state.calcs.reduce((a, c) => a + Store.totalP(c.lines), 0);
    assert('calcs: grand total sums every calc', Store.grandTotalP() === grand && grand > 0);
    const name = Store.deleteCalc(Store.state.calcs[0].id);
    assert('calcs: delete removes and picks a neighbour', name && Store.state.calcs.length === 2 && Store.calc(Store.state.active));
    Store.undo();
    assert('calcs: delete is undoable', Store.state.calcs.length === 3);
    assert('calcs: rename', Store.renameCalc(Store.state.calcs[0].id, 'Ward 3') && Store.state.calcs[0].name === 'Ward 3');
    assert('calcs: switchBy wraps around', (Store.switchTo(Store.state.calcs[2].id), Store.switchBy(1).ok) && Store.state.active === Store.state.calcs[0].id);
    Store.deleteCalc(Store.state.calcs[0].id); Store.deleteCalc(Store.state.calcs[0].id); Store.deleteCalc(Store.state.calcs[0].id);
    assert('calcs: deleting the last one leaves a fresh empty calc', Store.state.calcs.length === 1 && Store.state.lines.size === 0);

    reset();
    const ws = Store.serializeWorkspace();
    assert('persist: workspace serialises calcs', Array.isArray(ws.calcs) && ws.calcs.length === 1 && ws.v === SCHEMA_VERSION);
    const legacy = [['old-random-id', { req: 5, packs: 1, cost: 10, supplyPrice: 0, item: { n: 'Toujeo', t: 'قوي عاملة', u: 'Pen', s: 'Unified Purchase' } }], ['x', { item: { n: 'nope' } }], ['bad']];
    const hyd = Store.hydrateEntries(legacy);
    assert('migration: v4.5 entry remaps to current id', hyd.length === 1 && hyd[0][0] === toujeo.id);
    const hyd2 = Store.hydrateEntries([[apidra.id, { req: 1020, packs: 4 }]], true);
    assert('migration: legacy ceil packs become automatic', !hyd2[0][1].manual && hyd2[0][1].packs === 3);
    const hyd3 = Store.hydrateEntries([[apidra.id, { req: 1020, packs: 7 }]], true);
    assert('migration: legacy hand-edited packs stay manual', hyd3[0][1].manual && hyd3[0][1].packs === 7);
    localStorage.removeItem(KEYS.ws);
    localStorage.setItem(KEYS.orders, JSON.stringify([{ id: '1', name: 'Old A', items: [[concor.id, { req: 30, packs: 1 }]] }, { id: '2', name: 'Old B', items: [[apidra.id, { req: 600, packs: 2 }]] }]));
    localStorage.setItem(KEYS.calc, JSON.stringify([[concor.id, { req: 60, packs: 2 }]]));
    localStorage.setItem(KEYS.cur, '0');
    const lr = Store.load();
    assert('migration: v5 orders become calculations', lr.migrated && Store.state.calcs.length === 2 && Store.state.calcs[0].name === 'Old A' && Store.activeCalc().name === 'Old A' && Store.state.lines.get(concor.id).req === 60);
    localStorage.removeItem(KEYS.ws);
    localStorage.setItem(KEYS.orders, '[]');
    localStorage.setItem(KEYS.calc, JSON.stringify([[concor.id, { req: 30, packs: 1 }]]));
    localStorage.setItem(KEYS.cur, '-1');
    Store.load();
    assert('migration: unsaved draft is kept as a calculation', Store.state.calcs.length === 1 && Store.state.lines.size === 1);
    reset();
    const imp = Store.importEntries({ title: 'Legacy', items: legacy });
    assert('import: v5 file drops unknown, keeps valid, replaces empty calc', imp.ok && imp.count === 1 && imp.dropped === 2 && Store.state.calcs.length === 1 && Store.activeCalc().name === 'Legacy');
    const imp2 = Store.importEntries({ calcs: [{ name: 'X', items: [[concor.id, { req: 30, packs: 1, manual: false }]] }, { name: 'Y', items: [] }] });
    assert('import: 5.5 multi-calc file adds calculations', imp2.ok && imp2.calcs === 2 && Store.state.calcs.length === 3);

    reset();
    Store.state.prefs.addMode = 'unit';
    els.in.value = ''; App.armed = false; search();
    assert('omni: empty is IDLE', App.omniState === 'IDLE');
    els.in.value = 'concor'; App.armed = false; search();
    assert('omni: text is SEARCHING', App.omniState === 'SEARCHING');
    els.in.value = 'concor 5 x30'; App.armed = false; search();
    assert('omni: qty is ARMED_WITH_QTY', App.omniState === 'ARMED_WITH_QTY');
    assert('omni: target chip hidden with one calc', els.target.hidden);
    els.in.value = `${dyn.n} x2`; App.armed = false; search();
    assert('omni: share item without price NEEDS_PRICE', App.omniState === 'ARMED_NEEDS_PRICE');
    els.in.value = `${dyn.n} @450 x2`; App.armed = false; search();
    assert('omni: @price skips NEEDS_PRICE', App.omniState === 'ARMED_WITH_QTY');
    els.in.value = 'concor'; App.armed = false; search();
    press(els.in, 'Tab');
    assert('omni: Tab completes & arms', App.armed && App.omniState === 'ARMED_PENDING_QTY');
    els.in.value = 'concor 5 x30'; App.armed = false; search();
    press(els.in, 'Escape');
    assert('omni: Esc strips qty', els.in.value === 'concor 5' && App.omniState === 'SEARCHING');
    press(els.in, 'Escape');
    assert('omni: Esc again clears', els.in.value === '' && App.omniState === 'IDLE');
    els.in.value = 'concor 5 x30'; App.armed = false; search();
    press(els.in, 'Enter');
    assert('loop: Enter commits and returns to IDLE', Store.state.lines.get(concor.id).req === 30 && App.omniState === 'IDLE' && document.activeElement === els.in);
    els.in.value = 'concor 5 x5'; App.armed = false; search();
    press(els.in, 'Enter', { shift: true });
    assert('loop: Shift+Enter keeps query', els.in.value === 'concor 5 x5' && Store.state.lines.get(concor.id).req === 35);
    press(els.in, 'Enter');
    assert('loop: repeat Enter adds again', Store.state.lines.get(concor.id).req === 40);
    els.in.value = 'toujeo x900u'; App.armed = false; search();
    press(els.in, 'Enter');
    const tj = Store.state.lines.get(searchCatalog(App.db, 'toujeo')[0].id);
    assert('loop: insulin IU → pens (900u → 2)', tj && tj.packs === 2);
    els.in.value = 'concor 5 x2p'; App.armed = false; search();
    press(els.in, 'Enter');
    assert('loop: x2p adds packs', Store.state.lines.get(concor.id).req === 100);
    els.in.value = `${dyn.n} x2`; App.armed = false; search();
    press(els.in, 'Enter');
    assert('price: Enter reveals price field', !els.priceWrap.hidden && document.activeElement === els.price);
    els.price.value = '450';
    press(els.price, 'Enter');
    assert('price: Enter in price commits', Store.state.lines.has(dyn.id) && App.omniState === 'IDLE');

    const first = Store.activeCalc();
    const second = Store.newCalc().calc;
    Store.switchTo(first.id);
    els.in.value = 'concor 5 x30'; App.armed = false; search();
    assert('omni: target chip shows with several calcs', !els.target.hidden && els.target.textContent.includes(first.name));
    els.in.value = 'concor 5 x30 #2'; App.armed = false; search();
    assert('omni: #2 overrides the target chip', els.target.classList.contains('override') && els.target.textContent.includes(second.name));
    press(els.in, 'Enter');
    assert('loop: #2 adds to calc 2 without switching', second.lines.get(concor.id).req === 30 && Store.state.active === first.id);
    els.in.value = 'concor 5 x30 #9'; App.armed = false; search();
    assert('omni: unknown #n is flagged', els.target.classList.contains('bad') && els.hint.classList.contains('err'));
    press(els.in, 'Enter');
    assert('loop: unknown #n does not add', Store.state.lines.get(concor.id).req === 100);
    els.in.value = 'concor 5'; App.armed = false; search();
    const row = rowCache.get(concor.id);
    assert('row: shows badge for the other calc', row && row.querySelector(`.mb .num[data-cid="${second.id}"]`));
    row.querySelector(`.mb .num[data-cid="${second.id}"]`).click();
    assert('row: clicking the badge switches calc', Store.state.active === second.id);
    assert('rail: one tab per calc, active marked', els.railTrack.querySelectorAll('.tab').length === 2 && els.railTrack.querySelector('.tab.on').dataset.cid === second.id);

    els.in.value = 'concor'; search();
    moveSel(1);
    assert('select: down selects first', App.sel === 0 && els.in.getAttribute('aria-activedescendant') === `row-${App.results[0].id}`);
    moveSel(-1);
    assert('select: up wraps to last', App.sel === App.results.length - 1);
    const firstNode = rowCache.get(App.results[0].id);
    els.in.value = 'concor '; search();
    assert('render: surviving row keeps DOM node', rowCache.get(App.results[0].id) === firstNode);
    assert('a11y: listbox/option/combobox', els.res.getAttribute('role') === 'listbox' && firstNode.getAttribute('role') === 'option' && els.in.getAttribute('role') === 'combobox');
    els.in.value = ''; search();
    assert('idle: empty query shows idle panel', !!els.res.querySelector('[data-idle]') && App.results.length === 0);
    els.in.value = 'zzznonexistentxyz'; search();
    assert('empty: no-match names query', els.res.textContent.includes('zzznonexistentxyz'));
    openBoard();
    assert('board: renders a column per calc + new', els.boardCols.querySelectorAll('.col:not(.col-new)').length === 2 && els.boardCols.querySelector('.col-new'));
    els.boardFilter.value = 'toujeo'; renderBoard();
    assert('board: filter narrows to calcs holding the medicine', els.boardCols.querySelectorAll('.col:not(.col-new)').length === 1 && els.boardCols.querySelector('.col-item.hit'));
    els.boardFilter.value = '';
    closeBoard();
  } catch (err) {
    results.push({ name: `threw: ${err && err.message}`, pass: false });
  } finally {
    Store.restore(snap);
    Store.undoStack = undoSnap;
    Object.assign(Store.state.prefs, prefsSnap);
    Store.state.recent = recentSnap;
    lsSnap.forEach(([k, v]) => { if (v === null) localStorage.removeItem(k); else localStorage.setItem(k, v); });
    els.in.value = ''; App.armed = false; els.priceWrap.hidden = true;
    search(); renderTray(); renderModeSeg();
    $('toasts').innerHTML = '';
  }
  const pass = results.filter(r => r.pass).length;
  console.group(`%cLX self-test: ${pass}/${results.length} passed`, `color:${pass === results.length ? '#3ddc84' : '#ff5c5c'};font-weight:bold`);
  results.forEach(r => console[r.pass ? 'log' : 'error'](`${r.pass ? '✓' : '✗'} ${r.name}`));
  console.groupEnd();
  return results;
};
